#theme: jekyll-theme-minimal
#title: Dian Jin
#description: math student @UW-Madison

# Site settings
title: Your Site Title
description: A brief description of your site
url: https://example.com # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/ or /jekyll-site

# Build settings
theme: minima # the name of the theme you're using
plugins:
  - jekyll-seo-tag # add SEO meta tags to your pages
  - jekyll-sitemap # generate a sitemap for your site
  - jekyll-feed # generate an RSS feed for your site
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - _site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight

# Navigation links
header_pages:
  - about.md
  - contact.md

# Custom variables
my_custom_variable: "Hello, world!"
